// Generated by ../levels/combiner.py
import { Graph } from "./GDM-TS";
import {CustomNode } from "./customNode";
import { KEY_DEATH, KEY_END, KEY_START } from "./constants";

// ========= Nodes =========
export const HAND_MDP = new Graph();

HAND_MDP.addNode(new CustomNode(KEY_START, 0, 0, false, [], [], -1));
HAND_MDP.addNode(new CustomNode(KEY_DEATH, -1, 0, true, [], [], -1));
HAND_MDP.addNode(new CustomNode("idk-0", -1.5, 0, false, [], ["XX----------XXX", "XX----------XXX", "XX---XX-----XXX", "XX-#-XXXX---XXX", "XX-----XX------", "XXXX---XX------", "XXXX---XX-----#", "XXXX--#XX---XXX", "XXXX---XX---XXX", "-------XX---XXX", "&------XX---XXX"],4));
HAND_MDP.addNode(new CustomNode("1-0", -2.9, 0, false, [], ["----------", "----------", "----------", "----------", "----------", "----------", "----------", "----------", "----------", "----------", "----------"],1));
HAND_MDP.addNode(new CustomNode("1-1", -2.9, 0, false, [], ["-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------"],1));
HAND_MDP.addNode(new CustomNode("switch-0", -2.8, 0, false, [], ["-------------", "-------------", "-------------", "-------------", "-----*-------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------"],2));
HAND_MDP.addNode(new CustomNode("switch-1", -2.8, 0, false, [], ["-------------", "---------*---", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------"],2));
HAND_MDP.addNode(new CustomNode("switch-2", -2.8, 0, false, [], ["-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "---------*---", "-------------", "-------------", "-------------"],2));
HAND_MDP.addNode(new CustomNode("end-0", -0.0, 0, true, [], ["----------", "*---------", "*---------", "*---------", "*---------", "*---------", "*---------", "*---------", "*---------", "*---------", "**********"],1));
HAND_MDP.addNode(new CustomNode("end-1", -0.0, 0, true, [], ["-------------", "*------------", "*------------", "*------------", "*------------", "*------------", "*------------", "*------------", "*------------", "*------------", "*************"],1));
HAND_MDP.addNode(new CustomNode("enemy-0", -2.7, 0, false, [], ["-------------", "-------------", "-------------", "-------------", "-----#-------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------"],3));
HAND_MDP.addNode(new CustomNode("enemy-1", -2.7, 0, false, [], ["-------------", "---------#---", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------"],3));
HAND_MDP.addNode(new CustomNode("enemy-2", -2.7, 0, false, [], ["-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "---------#---", "-------------", "-------------", "-------------"],3));

// ========= Edges =========
HAND_MDP.addDefaultEdge("start", "end-0", [["end-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("start", "end-1", [["end-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("start", "1-0", [["1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("start", "1-1", [["1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("idk-0", "end-0", [["end-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("idk-0", "end-1", [["end-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("1-0", "switch-0", [["switch-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("1-0", "switch-1", [["switch-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("1-0", "switch-2", [["switch-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("1-1", "switch-0", [["switch-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("1-1", "switch-1", [["switch-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("1-1", "switch-2", [["switch-2", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("switch-0", "enemy-0", [["enemy-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-0", "enemy-1", [["enemy-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-0", "enemy-2", [["enemy-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-1", "enemy-0", [["enemy-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-1", "enemy-1", [["enemy-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-1", "enemy-2", [["enemy-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-2", "enemy-0", [["enemy-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-2", "enemy-1", [["enemy-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("switch-2", "enemy-2", [["enemy-2", 0.99], [KEY_DEATH, 0.01]]);


HAND_MDP.addDefaultEdge("enemy-0", "idk-0", [["idk-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("enemy-1", "idk-0", [["idk-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("enemy-2", "idk-0", [["idk-0", 0.99], [KEY_DEATH, 0.01]]);

