// Generated by ../levels/combiner.py
import { Graph } from "./GDM-TS";
import {CustomNode } from "./customNode";
import { KEY_DEATH, KEY_END, KEY_START } from "./constants";

// ========= Nodes =========
export const HAND_MDP = new Graph();

HAND_MDP.addNode(new CustomNode(KEY_START, 0, 0, false, [], [], -1));
HAND_MDP.addNode(new CustomNode(KEY_DEATH, -1, 0, true, [], [], -1));
HAND_MDP.addNode(new CustomNode("idk-0", -1.5, 0, false, [], ["XX----------XXX", "XX----------XXX", "XX---XX-----XXX", "XX-#-XXXX---XXX", "XX-----XX---&--", "XXXX---XX------", "XXXX---XX-----#", "XXXX--#XX---XXX", "XXXX---XX---XXX", "-------XX---XXX", "&------XX---XXX"],25));
HAND_MDP.addNode(new CustomNode("s-0", -3.7, 0, false, [], ["-------------", "-------------", "-------------", "-------------", "-----*-------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------"],1));
HAND_MDP.addNode(new CustomNode("s-1", -3.7, 0, false, [], ["-------------", "---------*---", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------"],1));
HAND_MDP.addNode(new CustomNode("s-2", -3.7, 0, false, [], ["-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "-------------", "---------*---", "-------------", "-------------", "-------------"],1));
HAND_MDP.addNode(new CustomNode("end-0", -0.0, 0, true, [], ["----------", "----------", "----------", "--******--", "--**&&**--", "--**&&**--", "--******--", "----------", "----------", "----------", "----------"],26));
HAND_MDP.addNode(new CustomNode("end-1", -0.0, 0, true, [], ["----------", "----------", "----------", "----------", "-******---", "-**&&**---", "-**&&**---", "-******---", "----------", "----------", "----------"],26));
HAND_MDP.addNode(new CustomNode("e-0", -3.6, 0, false, [], ["-----", "-----", "-----", "-----", "--#--", "-----", "-----", "-----", "-----", "-----", "-----"],2));
HAND_MDP.addNode(new CustomNode("e-1", -3.6, 0, false, [], ["-----", "-----", "-----", "-----", "-----", "-----", "--#--", "-----", "-----", "-----", "-----"],2));
HAND_MDP.addNode(new CustomNode("e-2", -3.6, 0, false, [], ["-----", "-----", "-----", "-----", "-----", "--#--", "-----", "-----", "-----", "-----", "-----"],2));
HAND_MDP.addNode(new CustomNode("e-3", -3.6, 0, false, [], ["-----", "-----", "-----", "-----", "-----", "-----", "-----", "-----", "--#--", "-----", "-----"],2));
HAND_MDP.addNode(new CustomNode("e2-0", -3.5, 0, false, [], ["--------", "--------", "--------", "--------", "--#-----", "--------", "--------", "--------", "---#----", "--------", "--------"],3));
HAND_MDP.addNode(new CustomNode("e2-1", -3.5, 0, false, [], ["--------", "--------", "--------", "--------", "---#----", "--------", "--#-----", "--------", "--------", "--------", "--------"],3));
HAND_MDP.addNode(new CustomNode("e2-2", -3.5, 0, false, [], ["--------", "--------", "-----#--", "--------", "--------", "--#-----", "--------", "--------", "--------", "--------", "--------"],3));
HAND_MDP.addNode(new CustomNode("e2-3", -3.5, 0, false, [], ["--------", "-----#--", "--------", "--------", "--------", "--------", "--------", "--------", "--#-----", "--------", "--------"],3));
HAND_MDP.addNode(new CustomNode("e3-0", -3.4, 0, false, [], ["------", "------", "----#-", "------", "--#---", "------", "------", "------", "---#--", "------", "------"],4));
HAND_MDP.addNode(new CustomNode("e3-1", -3.4, 0, false, [], ["------", "----#-", "------", "------", "---#--", "------", "--#---", "------", "------", "------", "------"],4));
HAND_MDP.addNode(new CustomNode("e3-2", -3.4, 0, false, [], ["------", "----#-", "------", "------", "------", "--#---", "------", "---#--", "------", "------", "------"],4));
HAND_MDP.addNode(new CustomNode("e3-3", -3.4, 0, false, [], ["------", "--#---", "------", "------", "---#--", "------", "------", "------", "--#---", "------", "------"],4));
HAND_MDP.addNode(new CustomNode("f-0", -3.3, 0, false, [], ["---------------------", "---------------------", "---------------------", "---------------------", "---------------------", "------------&--------", "---------------------", "---------------------", "---------------------", "---------------------", "---------------------"],5));
HAND_MDP.addNode(new CustomNode("f-1", -3.3, 0, false, [], ["---------------------", "---------------------", "---------------------", "---------------------", "---------------------", "---------------------", "---------------------", "----------------&----", "---------------------", "---------------------", "---------------------"],5));
HAND_MDP.addNode(new CustomNode("f-2", -3.3, 0, false, [], ["---------------------", "---------------------", "---------------------", "---------------------", "---------------------", "-----------&---------", "---------------------", "---------------------", "---------------------", "---------------------", "---------------------"],5));
HAND_MDP.addNode(new CustomNode("ld-f-0", -3.2, 0, false, [], ["-XXXXXXXXXXXXX-", "-XXXXXXXXXXXXX-", "---------------", "---------------", "-------&-------", "-------#-------", "---------------", "---------------", "---------------", "-XXXXXXXXXXXXX-", "-XXXXXXXXXXXXX-"],6));
HAND_MDP.addNode(new CustomNode("ld-f-1", -3.2, 0, false, [], ["-XXXXXXXXXXXXX-", "-XXXXXXXXXXXXX-", "-------&-------", "---------------", "-------#-------", "---------------", "---------------", "---------------", "---------------", "-XXXXXXXXXXXXX-", "-XXXXXXXXXXXXX-"],6));
HAND_MDP.addNode(new CustomNode("ld-f-2", -3.2, 0, false, [], ["-XXXXXXXXXXXXX-", "-XXXXXXXXXXXXX-", "---------------", "---------------", "---------------", "---------------", "-------#-------", "---------------", "-------&-------", "-XXXXXXXXXXXXX-", "-XXXXXXXXXXXXX-"],6));
HAND_MDP.addNode(new CustomNode("ld-s-0", -3.3, 0, false, [], ["XXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXX", "---------------", "---------------", "-------*-------", "-------#-------", "---------------", "---------------", "---------------", "XXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXX"],6));
HAND_MDP.addNode(new CustomNode("ld-s-1", -3.3, 0, false, [], ["XXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXX", "-------*-------", "---------------", "-------#-------", "---------------", "---------------", "---------------", "---------------", "XXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXX"],6));
HAND_MDP.addNode(new CustomNode("ld-s-2", -3.3, 0, false, [], ["XXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXX", "---------------", "---------------", "---------------", "---------------", "-------#-----*-", "---------------", "---------------", "XXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXX"],6));
HAND_MDP.addNode(new CustomNode("sp-0", -3.1, 0, false, [], ["^^^^^^^^", "^^^^^^^^", "^^^^^^^^", "^^^^^^^^", "^^^^^^^^", "-------*", "^^^^^^^^", "^^^^^^^^", "^^^^^^^^", "^^^^^^^^", "^^^^^^^^"],7));
HAND_MDP.addNode(new CustomNode("sp-1", -3.1, 0, false, [], ["^^^^^^^^^", "^^^^^^^^^", "^^^^^^^^^", "^^^^^^^^^", "^^^^^^^^^", "---*-----", "^^^^^^^^^", "^^^^^^^^^", "^^^^^^^^^", "^^^^^^^^^", "^^^^^^^^^"],7));
HAND_MDP.addNode(new CustomNode("ps-e1-0", -3.0, 0, false, [], ["-----------------", "-----------------", "-----------------", "-----------------", "------XXX--------", "------X#*--------", "------XXX-----&--", "-----------------", "-----------------", "-----------------", "-----------------"],8));
HAND_MDP.addNode(new CustomNode("ps-e1-1", -3.0, 0, false, [], ["-----------------", "-----------------", "-----------------", "-----------------", "------XXX--------", "------*#X--------", "------XXX-----&--", "-----------------", "-----------------", "-----------------", "-----------------"],8));
HAND_MDP.addNode(new CustomNode("e3-s-0", -2.9, 0, false, [], ["-----------------", "-----#-----------", "-----------------", "------*----------", "--#-------#------", "-----------------", "--------------&--", "-----------------", "-----------------", "-----------------", "-----------------"],9));
HAND_MDP.addNode(new CustomNode("e3-s-1", -2.9, 0, false, [], ["-----------------", "-----------------", "-----------------", "-----------------", "-----------------", "-----------------", "-----#--------&--", "----------#------", "-------*---------", "-----#-----------", "-----------------"],9));
HAND_MDP.addNode(new CustomNode("e2-s-0", -3.05, 0, false, [], ["-----------------", "-----#-----------", "-----------------", "------*----------", "----------#------", "-----------------", "--------------&--", "-----------------", "-----------------", "-----------------", "-----------------"],8));
HAND_MDP.addNode(new CustomNode("e2-s-1", -3.05, 0, false, [], ["-----------------", "-----------------", "-----------------", "-----------------", "-----------------", "-----------------", "-----#--------&--", "----------#------", "-------*---------", "-----------------", "-----------------"],8));
HAND_MDP.addNode(new CustomNode("ps-e2-0", -2.9, 0, false, [], ["-----------------", "-----------------", "-----------------", "-----------------", "------XXX--------", "------X#*---#----", "------XXX-----&--", "-----------------", "-----------------", "-----------------", "-----------------"],9));
HAND_MDP.addNode(new CustomNode("ps-e2-1", -2.9, 0, false, [], ["-----------------", "-----------------", "-----------------", "-----------------", "------XXX--------", "--#---*#X--------", "------XXX-----&--", "-----------------", "-----------------", "-----------------", "-----------------"],9));
HAND_MDP.addNode(new CustomNode("ps-e3-0", -2.84, 0, false, [], ["-----------------", "-----------------", "-----------------", "----------#------", "------XXX--------", "------X#*--#-----", "------XXX-----&--", "-----------------", "-----------------", "-----------------", "-----------------"],10));
HAND_MDP.addNode(new CustomNode("ps-e3-1", -2.84, 0, false, [], ["-----------------", "-----------------", "-----------------", "---#-------------", "------XXX--------", "--#---*#X--------", "------XXX-----&--", "-----------------", "-----------------", "-----------------", "-----------------"],10));
HAND_MDP.addNode(new CustomNode("ps-e1-d-0", -2.88, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "-----------------", "-----------------", "------XXX--------", "------X#*--------", "------XXX-----&--", "-----------------", "-----------------", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],10));
HAND_MDP.addNode(new CustomNode("ps-e1-d-1", -2.88, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "-----------------", "-----------------", "------XXX--------", "------*#X--------", "------XXX-----&--", "-----------------", "-----------------", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],10));
HAND_MDP.addNode(new CustomNode("e3-s-d-0", -2.8, 0, false, [], ["XXXXXXXXXXXXXXXXX", "-----#-----------", "-----------------", "------*----------", "--#-------#------", "-----------------", "--------------&--", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],10));
HAND_MDP.addNode(new CustomNode("e3-s-d-1", -2.8, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "-----------------", "-----#--------&--", "----------#------", "-------*---------", "-----#-----------", "XXXXXXXXXXXXXXXXX"],10));
HAND_MDP.addNode(new CustomNode("ps-e2-d-0", -2.75, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "-----------------", "-----------------", "------XXX--------", "------X#*---#----", "------XXX-----&--", "-----------------", "-----------------", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],11));
HAND_MDP.addNode(new CustomNode("ps-e2-d-1", -2.75, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "-----------------", "-----------------", "------XXX--------", "--#---*#X--------", "------XXX-----&--", "-----------------", "-----------------", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],11));
HAND_MDP.addNode(new CustomNode("ps-e3-d-0", -2.6, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "---------------&-", "----------#------", "------XXX--------", "------X#*-----#--", "------XXX-----&--", "-----------------", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],12));
HAND_MDP.addNode(new CustomNode("ps-e3-d-1", -2.6, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "---------------&-", "---#-------------", "------XXX--------", "------*#X--------", "-#----XXX-----&--", "-----------------", "-----------------", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],12));
HAND_MDP.addNode(new CustomNode("e4-s-d-0", -2.7, 0, false, [], ["XXXXXXXXXXXXXXXXX", "-----#-----------", "-----------------", "------*----------", "--#-------#------", "-----------------", "-------#------&--", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX"],11));
HAND_MDP.addNode(new CustomNode("e4-s-d-1", -2.7, 0, false, [], ["XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXX", "-----------------", "-----------------", "-----#--------&--", "----------#------", "-------*---------", "-----#-------#---", "-----------------"],11));
HAND_MDP.addNode(new CustomNode("pz-0", -1.9, 0, false, [], ["----------", "----------", "----------", "--------X-", "--------X-", "-----XXXX-", "------*-X-", "--------X-", "----------", "----------", "----------"],20));
HAND_MDP.addNode(new CustomNode("pz-1", -1.9, 0, false, [], ["----------", "----------", "----------", "----------", "----------", "-----XXXX-", "------*-X-", "--------X-", "----------", "----------", "----------"],20));
HAND_MDP.addNode(new CustomNode("pz-2", -1.9, 0, false, [], ["----------", "----XXXXX-", "-----*--X-", "--------X-", "----------", "----------", "----------", "----------", "----------", "----------", "----------"],20));
HAND_MDP.addNode(new CustomNode("pz-e-0", -1.7, 0, false, [], ["----------", "----------", "----------", "--------X-", "--------X-", "-----XXXX-", "-----#*-X-", "--------X-", "----------", "----------", "----------"],22));
HAND_MDP.addNode(new CustomNode("pz-e-1", -1.7, 0, false, [], ["----------", "----------", "----------", "----------", "----------", "-----XXXX-", "-----#*-X-", "--------X-", "----------", "----------", "----------"],22));
HAND_MDP.addNode(new CustomNode("pz-e-2", -1.7, 0, false, [], ["----------", "----XXXXX-", "----#*--X-", "--------X-", "----------", "----------", "----------", "----------", "----------", "----------", "----------"],22));
HAND_MDP.addNode(new CustomNode("pz-e2-0", -1.5, 0, false, [], ["----------", "----------", "----------", "--------X-", "--------X-", "-----XXXX-", "-----#*-X-", "--------X-", "----------", "-------#--", "----------"],24));
HAND_MDP.addNode(new CustomNode("pz-e2-1", -1.5, 0, false, [], ["----------", "----------", "----------", "----------", "----------", "-----XXXX-", "-----#*-X-", "--------X-", "----------", "--------#-", "----------"],24));
HAND_MDP.addNode(new CustomNode("pz-e2-2", -1.5, 0, false, [], ["----------", "----XXXXX-", "----#*--X-", "--------X-", "----------", "----------", "--------#-", "----------", "----------", "----------", "----------"],24));
HAND_MDP.addNode(new CustomNode("pz-b-0", -1.8, 0, false, [], ["^^^^^^^^^^^", "^^^^^^^^^^^", "------^^^--", "------^^^--", "^^^^--^^^--", "^^^^--^^^--", "^^^^--^^^--", "^^^^---&---", "^^^^-------", "^^^^^^^^^^^", "^^^^^^^^^^^"],21));
HAND_MDP.addNode(new CustomNode("pz-b-1", -1.8, 0, false, [], ["^^^^^^^^", "^^^^^^^^", "^^------", "^^--&---", "^^--^^--", "^^--^^--", "^^--^^--", "----^^--", "----^^--", "^^^^^^^^", "^^^^^^^^"],21));
HAND_MDP.addNode(new CustomNode("pz-b-2", -1.8, 0, false, [], ["^^^^^^^^^^", "^^^^^^^^^^", "^^^^^^^^^^", "--^^------", "--^^--&---", "--^^--^^--", "------^^--", "------^^--", "^^^^^^^^^^", "^^^^^^^^^^", "^^^^^^^^^^"],21));
HAND_MDP.addNode(new CustomNode("px-b-1-0", -1.6, 0, false, [], ["^^^^^^^^^^^", "^^^^^^^^^^^", "------^^^--", "------^^^--", "^^^^--^^^--", "^^^^--^^^--", "^^^^--^^^--", "^^^^---&---", "^^^^-------", "^^^^^^^^^^^", "^^^^^^^^^^^"],23));
HAND_MDP.addNode(new CustomNode("px-b-1-1", -1.6, 0, false, [], ["^^^^^^^^", "^^^^^^^^", "^^------", "^^--&---", "^^--^^--", "^^--^^--", "^^--^^--", "----^^--", "----^^--", "^^^^^^^^", "^^^^^^^^"],23));
HAND_MDP.addNode(new CustomNode("px-b-1-2", -1.6, 0, false, [], ["^^^^^^^^^^", "^^^^^^^^^^", "^^^^^^^^^^", "--^^------", "--^^--&---", "--^^--^^--", "------^^--", "------^^--", "^^^^^^^^^^", "^^^^^^^^^^", "^^^^^^^^^^"],23));
HAND_MDP.addNode(new CustomNode("pa1-0", -2.5, 0, false, [], ["--XX----------XXX", "--XX----------XXX", "--XX---XX-----XXX", "--XX---XXXX---XXX", "--XX-----XX---&--", "--XXXX---XX------", "--XXXX---XX------", "--XXXX---XX---XXX", "--XXXX---XX---XXX", "--&------XX---XXX", "---------XX---XXX"],13));
HAND_MDP.addNode(new CustomNode("pa1-1", -2.5, 0, false, [], ["--XX----------XXX", "--XX----------XXX", "--XX---XX-----XXX", "--XX---XXXX-&-XXX", "--XX-----XX------", "--XXXX---XX------", "--XXXX---XX------", "--XXXX---XX---XXX", "--XXXX---XX---XXX", "-----&---XX---XXX", "---------XX---XXX"],13));
HAND_MDP.addNode(new CustomNode("pa2-0", -2.5, 0, false, [], ["---------------XX", "-------&-------XX", "--XXXXXXXXX----XX", "--XXXXXXXXX----XX", "--XX-----------XX", "--XX-----------XX", "--XX----XXXXXXXXX", "--XX----XXXXXXXXX", "--XX--------&----", "--XX-------------", "--XXXXXXXXXXXXXXX"],13));
HAND_MDP.addNode(new CustomNode("pa2-1", -2.5, 0, false, [], ["---------------XX", "----&----------XX", "--XXXXXXXXX----XX", "--XXXXXXXXX----XX", "--XX-----------XX", "--XX-----------XX", "--XX----XXXXXXXXX", "--XX----XXXXXXXXX", "--XX-----&-------", "--XX-------------", "--XXXXXXXXXXXXXXX"],13));
HAND_MDP.addNode(new CustomNode("pa3-0", -2.5, 0, false, [], ["------X-------X", "--&---X-------X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X-------X---&", "--X-------X----"],13));
HAND_MDP.addNode(new CustomNode("pa3-1", -2.5, 0, false, [], ["------X-------X", "------X-------X", "--X---X---X---X", "--X-&-X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X--&X", "--X-------X----", "--X-------X----"],13));
HAND_MDP.addNode(new CustomNode("hardest-0", -1.25, 0, false, [], ["----------", "----------", "--^^------", "--^^----X-", "--^^----X-", "-&^^-XXXX-", "--^^-#*-X-", "--^^----X-", "--^^------", "-------#--", "----------"],25));
HAND_MDP.addNode(new CustomNode("hardest-1", -1.25, 0, false, [], ["----------", "----------", "--^^------", "--^^------", "--^^------", "-&^^-XXXX-", "--^^-#*-X-", "--^^----X-", "--^^------", "--------#-", "----------"],25));
HAND_MDP.addNode(new CustomNode("pa2-e-0", -2.44, 0, false, [], ["---------------XX", "-------&-------XX", "--XXXXXXXXX--#-XX", "--XXXXXXXXX----XX", "--XX-----------XX", "--XX-----------XX", "--XX----XXXXXXXXX", "--XX----XXXXXXXXX", "--XX--------&----", "--XX-------------", "--XXXXXXXXXXXXXXX"],14));
HAND_MDP.addNode(new CustomNode("pa2-e-1", -2.44, 0, false, [], ["---------------XX", "----&----------XX", "--XXXXXXXXX----XX", "--XXXXXXXXX----XX", "--XX-----------XX", "--XX-----------XX", "--XX-#--XXXXXXXXX", "--XX----XXXXXXXXX", "--XX-----&-------", "--XX-------------", "--XXXXXXXXXXXXXXX"],14));
HAND_MDP.addNode(new CustomNode("pa3-e-0", -2.4, 0, false, [], ["------X-------X", "--&---X-------X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X--#X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X-------X---&", "--X-------X----"],14));
HAND_MDP.addNode(new CustomNode("pa3-e-1", -2.4, 0, false, [], ["------X-------X", "------X-------X", "--X---X---X---X", "--X-&-X---X---X", "--X---X--#X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X--&X", "--X-------X----", "--X-------X----"],14));
HAND_MDP.addNode(new CustomNode("pa1-e-0", -2.48, 0, false, [], ["--XX----------XXX", "--XX----------XXX", "--XX---XX-----XXX", "--XX---XXXX---XXX", "--XX-----XX---&--", "--XXXX---XX------", "--XXXX---XX------", "--XXXX--#XX---XXX", "--XXXX---XX---XXX", "--&------XX---XXX", "---------XX---XXX"],14));
HAND_MDP.addNode(new CustomNode("pa1-e-1", -2.48, 0, false, [], ["--XX----------XXX", "--XX----------XXX", "--XX---XX-----XXX", "--XX-#-XXXX-&-XXX", "--XX-----XX------", "--XXXX---XX------", "--XXXX---XX------", "--XXXX---XX---XXX", "--XXXX---XX---XXX", "-----&---XX---XXX", "---------XX---XXX"],14));
HAND_MDP.addNode(new CustomNode("pa1-e2-s-0", -2.3, 0, false, [], ["--XX----------XXX", "--XX-------#-*XXX", "--XX---XX-----XXX", "--XX---XXXX---XXX", "--XX-----XX---&--", "--XXXX---XX------", "--XXXX---XX------", "--XXXX--#XX---XXX", "--XXXX---XX---XXX", "--&------XX---XXX", "---------XX---XXX"],15));
HAND_MDP.addNode(new CustomNode("pa1-e2-s-1", -2.3, 0, false, [], ["--XX----------XXX", "--XX----------XXX", "--XX---XX-----XXX", "--XX-#-XXXX-&-XXX", "--XX-----XX------", "--XXXX---XX------", "--XXXX---XX------", "--XXXX---XX---XXX", "--XXXX---XX-#-XXX", "-----&---XX-*-XXX", "---------XX---XXX"],15));
HAND_MDP.addNode(new CustomNode("pa3-e2-s-0", -2.3, 0, false, [], ["------X-------X", "--&---X-------X", "--X---X--*X---X", "--X---X--#X---X", "--X---X---X---X", "--X--#X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X-------X---&", "--X-------X----"],15));
HAND_MDP.addNode(new CustomNode("pa3-e2-s-1", -2.3, 0, false, [], ["------X-------X", "------X-------X", "--X---X---X---X", "--X-&-X--*X---X", "--X-#-X--#X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X---X", "--X---X---X--&X", "--X-------X----", "--X-------X----"],15));
HAND_MDP.addNode(new CustomNode("pa2-e2-s-0", -2.3, 0, false, [], ["---------------XX", "-------&-------XX", "--XXXXXXXXX--#-XX", "--XXXXXXXXX--*-XX", "--XX-----------XX", "--XX-----------XX", "--XX----XXXXXXXXX", "--XX----XXXXXXXXX", "--XX----#---&----", "--XX-------------", "--XXXXXXXXXXXXXXX"],15));
HAND_MDP.addNode(new CustomNode("pa2-e2-s-1", -2.3, 0, false, [], ["---------------XX", "----&-------#--XX", "--XXXXXXXXX----XX", "--XXXXXXXXX----XX", "--XX-----------XX", "--XX-----------XX", "--XX-#--XXXXXXXXX", "--XX-*--XXXXXXXXX", "--XX-----&-------", "--XX-------------", "--XXXXXXXXXXXXXXX"],15));
HAND_MDP.addNode(new CustomNode("m1-0", -2.2, 0, false, [], ["--XX------XX----", "--XX-----*XX----", "-----#XX------XX", "--XX--XX--XX--XX", "--XX------XX----", "------XX------XX", "--XX--XX-&XX--XX", "--XX------XX----", "-----#XX------XX", "--XX--XX--XX--XX", "--XX------XX----"],16));
HAND_MDP.addNode(new CustomNode("m1-1", -2.2, 0, false, [], ["--XX------XX----", "--XX------XX----", "------XX------XX", "--XX--XX--XX--XX", "--XX-&---#XX----", "------XX------XX", "--XX--XX--XX-*XX", "--XX------XX----", "------XX------XX", "--XX--XX-#XX--XX", "--XX------XX----"],16));
HAND_MDP.addNode(new CustomNode("m1-m-0", -2.1, 0, false, [], ["--XX------XX----", "--XX-----*XX----", "-----#XX------XX", "--XX--XX--XX--XX", "--XX---#--XX----", "------XX------XX", "--XX--XX-&XX--XX", "--XX------XX----", "-----#XX----#-XX", "--XX--XX--XX--XX", "--XX------XX----"],17));
HAND_MDP.addNode(new CustomNode("m1-m-1", -2.1, 0, false, [], ["--XX------XX----", "--XX---#--XX----", "------XX------XX", "--XX--XX--XX--XX", "--XX-&---#XX----", "------XX------XX", "--XX--XX--XX-*XX", "--XX---#--XX----", "------XX------XX", "--XX--XX-#XX--XX", "--XX------XX----"],17));
HAND_MDP.addNode(new CustomNode("m1-h-0", -2.04, 0, false, [], ["--XX------XX----", "--XX-----*XX-#--", "-----#XX------XX", "--XX--XX--XX--XX", "--XX------XX----", "------XX------XX", "--XX--XX-&XX--XX", "--XX------XX-#--", "-----#XX------XX", "--XX--XX--XX--XX", "--XX------XX----"],18));
HAND_MDP.addNode(new CustomNode("m1-h-1", -2.04, 0, false, [], ["--XX------XX----", "--XX--#---XX----", "------XX------XX", "--XX--XX--XX--XX", "--XX-&---#XX----", "--#---XX------XX", "--XX--XX--XX-*XX", "--XX------XX----", "--#---XX------XX", "--XX--XX-#XX--XX", "--XX------XX----"],18));
HAND_MDP.addNode(new CustomNode("m2-0", -2.2, 0, false, [], ["------------X---", "---X-------XXX--", "--XXX---X---X---", "---X---XXX-----&", "--------X---X---", "------#----XXX--", "---X--------X---", "--XXX---X-----#-", "---X---XXX--X---", "--------X--XXX--", "------------X---"],16));
HAND_MDP.addNode(new CustomNode("m2-1", -2.2, 0, false, [], ["------------X---", "---X--#----XXX--", "--XXX---X---X---", "---X---XXX-----&", "--------X---X---", "-----------XXX--", "---X--------X---", "--XXX---X-------", "---X---XXX--X---", "-----#--X--XXX--", "------------X---"],16));
HAND_MDP.addNode(new CustomNode("m2-m-0", -2.1, 0, false, [], ["-------#----X---", "---X-------XXX--", "--XXX---X---X---", "---X---XXX-----&", "--------X---X---", "------#----XXX--", "---X--------X---", "--XXX---X-*---#-", "---X---XXX--X---", "--------X--XXX--", "------------X---"],17));
HAND_MDP.addNode(new CustomNode("m2-m-1", -2.1, 0, false, [], ["------------X---", "---X--#---*XXX--", "--XXX---X---X---", "---X---XXX-----&", "--------X---X---", "---#-------XXX--", "---X--------X---", "--XXX---X-------", "---X---XXX--X---", "-----#--X--XXX--", "------------X---"],17));
HAND_MDP.addNode(new CustomNode("m2-h-0", -2.08, 0, false, [], ["-------#----X---", "---X------*XXX--", "--XXX---X---X---", "---X---XXX-----&", "--------X---X---", "------#----XXX--", "---X--------X---", "--XXX---X-*---#-", "---X---XXX--X---", "--------X--XXX--", "---#--------X---"],18));
HAND_MDP.addNode(new CustomNode("m2-h-1", -2.08, 0, false, [], ["------------X---", "---X--#---*XXX--", "--XXX---X---X---", "---X---XXX-----&", "--------X---X---", "---#----*--XXX--", "---X--------X---", "--XXX---X-------", "---X---XXX--X---", "-----#--X--XXX--", "------------X---"],18));
HAND_MDP.addNode(new CustomNode("m3-0", -2.2, 0, false, [], ["^-----^-----^--^", "----^-----^-----", "--^-----^---*-^-", "^-----^-#---^---", "-&--^-----^----&", "--^-----^-----^-", "^-----^-----^---", "----^-----^-----", "--^-----^-----^-", "^-----^-----^---", "----^-----^----^"],16));
HAND_MDP.addNode(new CustomNode("m3-1", -2.2, 0, false, [], ["^-----^-----^--^", "----^-----^-----", "--^-----^-----^-", "^-----^-----^---", "----^-----^----&", "--^-----^-----^-", "^-----^-----^---", "-&--^---#-^-----", "--^-----^-*---^-", "^-----^-----^---", "----^-----^----^"],16));
HAND_MDP.addNode(new CustomNode("m3-m-0", -2.1, 0, false, [], ["^-----^-#---^--^", "----^-----^-----", "--^-----^---*-^-", "^-----^-#---^--&", "-&--^-----^-----", "--^-----^-----^-", "^-----^-----^---", "----^-----^-----", "--^-----^-----^-", "^-----^-----^---", "----^-----^----^"],17));
HAND_MDP.addNode(new CustomNode("m3-m-1", -2.1, 0, false, [], ["^-----^-----^--^", "----^-----^-----", "--^-----^-----^-", "^-----^-----^---", "----^-----^-----", "--^-----^-----^-", "^-----^-----^---", "-&--^---#-^----&", "--^-----^-*---^-", "^-----^-----^---", "----^---#-^----^"],17));
HAND_MDP.addNode(new CustomNode("m3-h-0", -1.9, 0, false, [], ["^--#--^-#---^--^", "----^-----^-----", "--^-----^---*-^-", "^-----^-#---^---", "-&--^-----^---#-", "--^-----^-----^-", "^--#--^-----^--&", "----^--#--^-----", "--^-----^-----^-", "^--#--^-----^---", "----^-----^----^"],19));
HAND_MDP.addNode(new CustomNode("m3-h-1", -1.9, 0, false, [], ["^-----^-----^--^", "----^--#--^-----", "--^-----^-#---^-", "^#----^-----^---", "----^--#--^----&", "--^-----^-----^-", "^-----^-----^---", "-&--^---#-^---#-", "--^-----^-*---^-", "^-----^-----^---", "----^---#-^----^"],19));

// ========= Edges =========
HAND_MDP.addDefaultEdge("start", "s-0", [["s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("start", "s-1", [["s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("start", "s-2", [["s-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("idk-0", "end-0", [["end-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("idk-0", "end-1", [["end-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("s-0", "e-0", [["e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-0", "e-1", [["e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-0", "e-2", [["e-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-0", "e-3", [["e-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-1", "e-0", [["e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-1", "e-1", [["e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-1", "e-2", [["e-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-1", "e-3", [["e-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-2", "e-0", [["e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-2", "e-1", [["e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-2", "e-2", [["e-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("s-2", "e-3", [["e-3", 0.99], [KEY_DEATH, 0.01]]);


HAND_MDP.addDefaultEdge("e-0", "e2-0", [["e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-0", "e2-1", [["e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-0", "e2-2", [["e2-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-0", "e2-3", [["e2-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-1", "e2-0", [["e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-1", "e2-1", [["e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-1", "e2-2", [["e2-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-1", "e2-3", [["e2-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-2", "e2-0", [["e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-2", "e2-1", [["e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-2", "e2-2", [["e2-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-2", "e2-3", [["e2-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-3", "e2-0", [["e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-3", "e2-1", [["e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-3", "e2-2", [["e2-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e-3", "e2-3", [["e2-3", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("e2-0", "e3-0", [["e3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-0", "e3-1", [["e3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-0", "e3-2", [["e3-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-0", "e3-3", [["e3-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-1", "e3-0", [["e3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-1", "e3-1", [["e3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-1", "e3-2", [["e3-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-1", "e3-3", [["e3-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-2", "e3-0", [["e3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-2", "e3-1", [["e3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-2", "e3-2", [["e3-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-2", "e3-3", [["e3-3", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-3", "e3-0", [["e3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-3", "e3-1", [["e3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-3", "e3-2", [["e3-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-3", "e3-3", [["e3-3", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("e3-0", "f-0", [["f-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-0", "f-1", [["f-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-0", "f-2", [["f-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-1", "f-0", [["f-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-1", "f-1", [["f-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-1", "f-2", [["f-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-2", "f-0", [["f-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-2", "f-1", [["f-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-2", "f-2", [["f-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-3", "f-0", [["f-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-3", "f-1", [["f-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-3", "f-2", [["f-2", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("f-0", "ld-f-0", [["ld-f-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-0", "ld-f-1", [["ld-f-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-0", "ld-f-2", [["ld-f-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-1", "ld-f-0", [["ld-f-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-1", "ld-f-1", [["ld-f-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-1", "ld-f-2", [["ld-f-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-2", "ld-f-0", [["ld-f-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-2", "ld-f-1", [["ld-f-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-2", "ld-f-2", [["ld-f-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-0", "ld-s-0", [["ld-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-0", "ld-s-1", [["ld-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-0", "ld-s-2", [["ld-s-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-1", "ld-s-0", [["ld-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-1", "ld-s-1", [["ld-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-1", "ld-s-2", [["ld-s-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-2", "ld-s-0", [["ld-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-2", "ld-s-1", [["ld-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("f-2", "ld-s-2", [["ld-s-2", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ld-f-0", "sp-0", [["sp-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-f-0", "sp-1", [["sp-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-f-1", "sp-0", [["sp-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-f-1", "sp-1", [["sp-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-f-2", "sp-0", [["sp-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-f-2", "sp-1", [["sp-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ld-s-0", "sp-0", [["sp-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-s-0", "sp-1", [["sp-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-s-1", "sp-0", [["sp-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-s-1", "sp-1", [["sp-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-s-2", "sp-0", [["sp-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ld-s-2", "sp-1", [["sp-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("sp-0", "e2-s-0", [["e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("sp-0", "e2-s-1", [["e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("sp-1", "e2-s-0", [["e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("sp-1", "e2-s-1", [["e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("sp-0", "ps-e1-0", [["ps-e1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("sp-0", "ps-e1-1", [["ps-e1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("sp-1", "ps-e1-0", [["ps-e1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("sp-1", "ps-e1-1", [["ps-e1-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ps-e1-0", "e3-s-0", [["e3-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e1-0", "e3-s-1", [["e3-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e1-1", "e3-s-0", [["e3-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e1-1", "e3-s-1", [["e3-s-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("e3-s-0", "ps-e3-0", [["ps-e3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-0", "ps-e3-1", [["ps-e3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-1", "ps-e3-0", [["ps-e3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-1", "ps-e3-1", [["ps-e3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-0", "ps-e1-d-0", [["ps-e1-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-0", "ps-e1-d-1", [["ps-e1-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-1", "ps-e1-d-0", [["ps-e1-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-1", "ps-e1-d-1", [["ps-e1-d-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("e2-s-0", "ps-e2-0", [["ps-e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-s-0", "ps-e2-1", [["ps-e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-s-1", "ps-e2-0", [["ps-e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e2-s-1", "ps-e2-1", [["ps-e2-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ps-e2-0", "e3-s-d-0", [["e3-s-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-0", "e3-s-d-1", [["e3-s-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-1", "e3-s-d-0", [["e3-s-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-1", "e3-s-d-1", [["e3-s-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-0", "ps-e1-d-0", [["ps-e1-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-0", "ps-e1-d-1", [["ps-e1-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-1", "ps-e1-d-0", [["ps-e1-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-1", "ps-e1-d-1", [["ps-e1-d-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ps-e3-0", "e4-s-d-0", [["e4-s-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-0", "e4-s-d-1", [["e4-s-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-1", "e4-s-d-0", [["e4-s-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-1", "e4-s-d-1", [["e4-s-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-0", "ps-e2-d-0", [["ps-e2-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-0", "ps-e2-d-1", [["ps-e2-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-1", "ps-e2-d-0", [["ps-e2-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-1", "ps-e2-d-1", [["ps-e2-d-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ps-e1-d-0", "e4-s-d-0", [["e4-s-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e1-d-0", "e4-s-d-1", [["e4-s-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e1-d-1", "e4-s-d-0", [["e4-s-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e1-d-1", "e4-s-d-1", [["e4-s-d-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("e3-s-d-0", "ps-e2-d-0", [["ps-e2-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-d-0", "ps-e2-d-1", [["ps-e2-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-d-1", "ps-e2-d-0", [["ps-e2-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e3-s-d-1", "ps-e2-d-1", [["ps-e2-d-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ps-e2-d-0", "ps-e3-d-0", [["ps-e3-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-d-0", "ps-e3-d-1", [["ps-e3-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-d-1", "ps-e3-d-0", [["ps-e3-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e2-d-1", "ps-e3-d-1", [["ps-e3-d-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("ps-e3-d-0", "pa1-0", [["pa1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-0", "pa1-1", [["pa1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-1", "pa1-0", [["pa1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-1", "pa1-1", [["pa1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-0", "pa3-0", [["pa3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-0", "pa3-1", [["pa3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-1", "pa3-0", [["pa3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-1", "pa3-1", [["pa3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-0", "pa2-0", [["pa2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-0", "pa2-1", [["pa2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-1", "pa2-0", [["pa2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("ps-e3-d-1", "pa2-1", [["pa2-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("e4-s-d-0", "ps-e3-d-0", [["ps-e3-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e4-s-d-0", "ps-e3-d-1", [["ps-e3-d-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e4-s-d-1", "ps-e3-d-0", [["ps-e3-d-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("e4-s-d-1", "ps-e3-d-1", [["ps-e3-d-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pz-0", "pz-b-0", [["pz-b-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-0", "pz-b-1", [["pz-b-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-0", "pz-b-2", [["pz-b-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-1", "pz-b-0", [["pz-b-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-1", "pz-b-1", [["pz-b-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-1", "pz-b-2", [["pz-b-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-2", "pz-b-0", [["pz-b-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-2", "pz-b-1", [["pz-b-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-2", "pz-b-2", [["pz-b-2", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pz-e-0", "px-b-1-0", [["px-b-1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-0", "px-b-1-1", [["px-b-1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-0", "px-b-1-2", [["px-b-1-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-1", "px-b-1-0", [["px-b-1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-1", "px-b-1-1", [["px-b-1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-1", "px-b-1-2", [["px-b-1-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-2", "px-b-1-0", [["px-b-1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-2", "px-b-1-1", [["px-b-1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e-2", "px-b-1-2", [["px-b-1-2", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pz-e2-0", "idk-0", [["idk-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-1", "idk-0", [["idk-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-2", "idk-0", [["idk-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-0", "hardest-0", [["hardest-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-0", "hardest-1", [["hardest-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-1", "hardest-0", [["hardest-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-1", "hardest-1", [["hardest-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-2", "hardest-0", [["hardest-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-e2-2", "hardest-1", [["hardest-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pz-b-0", "pz-e-0", [["pz-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-0", "pz-e-1", [["pz-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-0", "pz-e-2", [["pz-e-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-1", "pz-e-0", [["pz-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-1", "pz-e-1", [["pz-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-1", "pz-e-2", [["pz-e-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-2", "pz-e-0", [["pz-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-2", "pz-e-1", [["pz-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pz-b-2", "pz-e-2", [["pz-e-2", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("px-b-1-0", "pz-e2-0", [["pz-e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-0", "pz-e2-1", [["pz-e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-0", "pz-e2-2", [["pz-e2-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-1", "pz-e2-0", [["pz-e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-1", "pz-e2-1", [["pz-e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-1", "pz-e2-2", [["pz-e2-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-2", "pz-e2-0", [["pz-e2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-2", "pz-e2-1", [["pz-e2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("px-b-1-2", "pz-e2-2", [["pz-e2-2", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa1-0", "pa3-e-0", [["pa3-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-0", "pa3-e-1", [["pa3-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-1", "pa3-e-0", [["pa3-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-1", "pa3-e-1", [["pa3-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-0", "pa2-e-0", [["pa2-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-0", "pa2-e-1", [["pa2-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-1", "pa2-e-0", [["pa2-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-1", "pa2-e-1", [["pa2-e-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa2-0", "pa1-e-0", [["pa1-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-0", "pa1-e-1", [["pa1-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-1", "pa1-e-0", [["pa1-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-1", "pa1-e-1", [["pa1-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-0", "pa3-e-0", [["pa3-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-0", "pa3-e-1", [["pa3-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-1", "pa3-e-0", [["pa3-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-1", "pa3-e-1", [["pa3-e-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa3-0", "pa1-e-0", [["pa1-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-0", "pa1-e-1", [["pa1-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-1", "pa1-e-0", [["pa1-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-1", "pa1-e-1", [["pa1-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-0", "pa2-e-0", [["pa2-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-0", "pa2-e-1", [["pa2-e-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-1", "pa2-e-0", [["pa2-e-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-1", "pa2-e-1", [["pa2-e-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("hardest-0", "end-0", [["end-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("hardest-0", "end-1", [["end-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("hardest-1", "end-0", [["end-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("hardest-1", "end-1", [["end-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa2-e-0", "pa3-e2-s-0", [["pa3-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e-0", "pa3-e2-s-1", [["pa3-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e-1", "pa3-e2-s-0", [["pa3-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e-1", "pa3-e2-s-1", [["pa3-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e-0", "pa2-e2-s-0", [["pa2-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e-0", "pa2-e2-s-1", [["pa2-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e-1", "pa2-e2-s-0", [["pa2-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e-1", "pa2-e2-s-1", [["pa2-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa3-e-0", "pa1-e2-s-0", [["pa1-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e-0", "pa1-e2-s-1", [["pa1-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e-1", "pa1-e2-s-0", [["pa1-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e-1", "pa1-e2-s-1", [["pa1-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e-0", "pa2-e2-s-0", [["pa2-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e-0", "pa2-e2-s-1", [["pa2-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e-1", "pa2-e2-s-0", [["pa2-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e-1", "pa2-e2-s-1", [["pa2-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa1-e-0", "pa1-e2-s-0", [["pa1-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e-0", "pa1-e2-s-1", [["pa1-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e-1", "pa1-e2-s-0", [["pa1-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e-1", "pa1-e2-s-1", [["pa1-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e-0", "pa3-e2-s-0", [["pa3-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e-0", "pa3-e2-s-1", [["pa3-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e-1", "pa3-e2-s-0", [["pa3-e2-s-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e-1", "pa3-e2-s-1", [["pa3-e2-s-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa1-e2-s-0", "m1-0", [["m1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-0", "m1-1", [["m1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-1", "m1-0", [["m1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-1", "m1-1", [["m1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-0", "m3-0", [["m3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-0", "m3-1", [["m3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-1", "m3-0", [["m3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-1", "m3-1", [["m3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-0", "m2-0", [["m2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-0", "m2-1", [["m2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-1", "m2-0", [["m2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa1-e2-s-1", "m2-1", [["m2-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa3-e2-s-0", "m3-0", [["m3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e2-s-0", "m3-1", [["m3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e2-s-1", "m3-0", [["m3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e2-s-1", "m3-1", [["m3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e2-s-0", "m2-0", [["m2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e2-s-0", "m2-1", [["m2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e2-s-1", "m2-0", [["m2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa3-e2-s-1", "m2-1", [["m2-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("pa2-e2-s-0", "m1-0", [["m1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-0", "m1-1", [["m1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-1", "m1-0", [["m1-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-1", "m1-1", [["m1-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-0", "m3-0", [["m3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-0", "m3-1", [["m3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-1", "m3-0", [["m3-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-1", "m3-1", [["m3-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-0", "m2-0", [["m2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-0", "m2-1", [["m2-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-1", "m2-0", [["m2-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("pa2-e2-s-1", "m2-1", [["m2-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m1-0", "m3-m-0", [["m3-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-0", "m3-m-1", [["m3-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-1", "m3-m-0", [["m3-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-1", "m3-m-1", [["m3-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-0", "m2-m-0", [["m2-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-0", "m2-m-1", [["m2-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-1", "m2-m-0", [["m2-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-1", "m2-m-1", [["m2-m-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m1-m-0", "m2-h-0", [["m2-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-m-0", "m2-h-1", [["m2-h-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-m-1", "m2-h-0", [["m2-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-m-1", "m2-h-1", [["m2-h-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m1-h-0", "m3-h-0", [["m3-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-h-0", "m3-h-1", [["m3-h-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-h-1", "m3-h-0", [["m3-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m1-h-1", "m3-h-1", [["m3-h-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m2-0", "m1-m-0", [["m1-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-0", "m1-m-1", [["m1-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-1", "m1-m-0", [["m1-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-1", "m1-m-1", [["m1-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-0", "m3-m-0", [["m3-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-0", "m3-m-1", [["m3-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-1", "m3-m-0", [["m3-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-1", "m3-m-1", [["m3-m-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m2-m-0", "m1-h-0", [["m1-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-m-0", "m1-h-1", [["m1-h-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-m-1", "m1-h-0", [["m1-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-m-1", "m1-h-1", [["m1-h-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m2-h-0", "m3-h-0", [["m3-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-h-0", "m3-h-1", [["m3-h-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-h-1", "m3-h-0", [["m3-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m2-h-1", "m3-h-1", [["m3-h-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m3-0", "m1-m-0", [["m1-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-0", "m1-m-1", [["m1-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-1", "m1-m-0", [["m1-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-1", "m1-m-1", [["m1-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-0", "m2-m-0", [["m2-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-0", "m2-m-1", [["m2-m-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-1", "m2-m-0", [["m2-m-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-1", "m2-m-1", [["m2-m-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m3-m-0", "m2-h-0", [["m2-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-m-0", "m2-h-1", [["m2-h-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-m-1", "m2-h-0", [["m2-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-m-1", "m2-h-1", [["m2-h-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-m-0", "m1-h-0", [["m1-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-m-0", "m1-h-1", [["m1-h-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-m-1", "m1-h-0", [["m1-h-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-m-1", "m1-h-1", [["m1-h-1", 0.99], [KEY_DEATH, 0.01]]);

HAND_MDP.addDefaultEdge("m3-h-0", "pz-0", [["pz-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-h-0", "pz-1", [["pz-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-h-0", "pz-2", [["pz-2", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-h-1", "pz-0", [["pz-0", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-h-1", "pz-1", [["pz-1", 0.99], [KEY_DEATH, 0.01]]);
HAND_MDP.addDefaultEdge("m3-h-1", "pz-2", [["pz-2", 0.99], [KEY_DEATH, 0.01]]);

